apiVersion: v1
kind: Service
metadata:
  name: harness-demo-app
  namespace: {{ .Values.namespace }}
  labels:
    app: harness-demo-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: harness-demo-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.probes.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
